version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lifehub_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lifehub_db
      MYSQL_USER: lifehub_user
      MYSQL_PASSWORD: lifehub_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: lifehub_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: lifehub_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: lifehub_user
      MYSQL_PASSWORD: lifehub_password
      MYSQL_DATABASE: lifehub_db
      SECRET_KEY: your-super-secret-key-change-in-production
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - mysql
      - redis
    volumes:
      - ./app:/app/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
  redis_data: 